name = "roll-dorado-casino-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.ch"
HMAC_KEY = "7fac7d5a927d1a34a526c8e42524495217e6267bff381237e1c4201501b973ee"
COOKIE_NAME = "zbg"
PLAY_PATH = "play-now"
BUTTON_ID = "p7f4b5f73a7ccdccf09bfb831b5daf265"
GATE_SALT = "f47553dfabaf5689"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "71au"
CTA_SELECTOR = ".play-button"
